### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by Doooooris** [UBC-MDS/CleanPy#19]
Very good job! Clear explanation and documentation of your package!

- test_locate_na.py: Consider some extreme cases, like all input data is N/A
- test_replace_na.py: Need to test output calculation is correct for mean, median, etc... Additionally, need to test the output, for example, make sure output is not equal to input. Moreover, need to test if the input is making sense. 
- test_summary.py: Need to test input.

**Comment by tungpatrick** [comment]
Thank you for your feedback!

**Comment by heathervant** [comment]
Thanks ! I will test the input in the code using 
if isinstance(data, pd.DataFrame) == False:
       raise NotImplementedError("Input should be a pandas dataframe. Use pd.DataFrame(data)")

and add a test to the test script
